### ISSUE TITLE
Role Selection broken link

### ISSUE THREAD

**Issue by rahulmaheswaran** [dca123/matchmaker-client#17]
I get the following error for this url:
https://lobbyfinder.devinda.me/roleSelection

 "An unexpected error has occurred"
 
 Screenshot attached. 

![unknown](https://user-images.githubusercontent.com/57580576/108797614-95c22580-7559-11eb-8a60-fed91daf3fb5.png)

Rest of the site works fine, nice job!

**Comment by dca123** [comment]
Thank you for reporting. Looks like an issue from migrating /index -> /login. Should be fixed by replacing the URLs and adding callbacks on the authentication requests.
